### ISSUE TITLE
what if my client secret has exposed?

### ISSUE THREAD

**Issue by behumble** [jjNford/chrome-ex-oauth2#4]
this implementation looks great.
but I have a question.
chrome extension is distributed in ZIP with javascript source inside.
is there any way to avoid my client secret being exposed?

**Comment by whoisjuan** [comment]
No solution to this problem (or anything that uses JS for that matter). The only possible solution is if you own the endpoint. If that's the case you can do some sort of local hashing and un-encrypt server side.
You could also obfuscate or minify the code but that's only helpful for casual lookers. Serious threats won't be reduced by this approach.
This could be solved if Google changes their final file format to something that is not as easy to unbundle but I don't see that happening anytime soon.

**Comment by behumble** [comment]
Cleared. thanks.
